Result 패턴

ENUM보다는 sealed class를 준비하면 더 디테일한 에러 핸들링 가능
sealed 는 hasCode, == 등을 사용할 수 있음

Result 클래스 사용

- 성공시에는 데이터, 실패시에는 에러정보를 담는 객체 정의

1. 타입 안전성 향상
2. 에러 처리 강제성(컴파일러가 모든 케이스 처리 강제)
3. 에러타입의 명확한 문서화
4. try-catch 남용 방지
5. 비즈니스 로직과 에러처리 분리
6. 옵셔널 타입 사용 감소
7. 테스트 용이성

```dart
sealed class Result<T> {
  factory Result.success(T data) = Success;

  factory Result.error(String message) = Error;
}

class Success<T> implements Result<T> {
  final T data;

  Success(this.data);
}

class Error<T> implements Result<T> {
  final String message;

  Error(this.message);
}

Result<int> calculate(int a, int b) {
  try {
    if (a == 0) {
      return Result.error('a is not zero');
    }
    if (b == 0) {
      return Result.error('b is not zero');
    }
    return Result.success(a ~/ b);
  } catch (e) {
    return Result.error('예상치 못한 에러');
  }
}

void main() {
  final Result<int> result = calculate(1, 10);
  switch (result) {
    case Success<int>():
      print(result.data);
    case Error<int>():
      print(result.message);
  }
}
```

Result 패턴을 도입한 곳에서는 응답 객체를 Result 클래스로 랩핑하기
ex) Future<Result<List<Photo>> fetch(String query);

freezed를 활용한 result 클래스
응용 1

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'result.freezed.dart';

@freezed
sealed class Result<T> with _$Result<T> {
  const factory Result.success(T data) = Success;

  const factory Result.error(String e) = Error;
}
```

freezed를 활용한 result 클래스
응용 2

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'result.freezed.dart';

@freezed
sealed class Result<D, E> with _$Result<D, E> {
  const factory Result.success(D data) = Success;

  const factory Result.error(E error) = Error;
}

```

예시
Future<Result<List<Todo>, String>> getTodos();
=> 성공시 List<Todo>를 반환하고 실패하면 String 에러 메세지를 반환함

enum을 활용해서도 sealed class 준비 가능

```dart
enum NetworkError {
  requestTimeout,
  unknown,
}

abstract interface class PhotoRepository {
  Future<Result<List<Photo>, NetworkError>> getPhotos();
}
```

enum을 활용한 경우 try -catch를 활용해서 2가지 이상의 에러를 리턴할 수 있다.
